version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chatflow-postgres
    environment:
      POSTGRES_DB: chatflow_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatflow-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: chatflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatflow-network

  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: chatflow-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatflow_pro
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend/logs:/app/logs
    networks:
      - chatflow-network

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: chatflow-frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_WS_URL: ws://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chatflow-network

  # WhatsApp Service
  whatsapp-service:
    build:
      context: ../whatsapp-service
      dockerfile: ../docker/Dockerfile.whatsapp
    container_name: chatflow-whatsapp
    environment:
      NODE_ENV: production
      PORT: 3001
      BACKEND_URL: http://backend:5000
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - backend
      - redis
    volumes:
      - whatsapp_sessions:/app/sessions
    networks:
      - chatflow-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: chatflow-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - whatsapp-service
    networks:
      - chatflow-network

volumes:
  postgres_data:
  redis_data:
  whatsapp_sessions:

networks:
  chatflow-network:
    driver: bridge 